### ISSUE TITLE
Two questions about your fork

### ISSUE THREAD

**Issue by asakura42** [Dr4iv3rNope/NotSoAndroidAyuGram#3]
1. It seems that you use your own [TMessagesProj/google-services.json](https://github.com/AyuGram/AyuGram4A/compare/rewrite...Dr4iv3rNope:NotSoAndroidAyuGram:rewrite#diff-947e91ba72891c37875c6c38ed8f677b222a547b211ba8e2603f1f5b15505029). Is it secure to use your builds till this file is not open?
2. In README you wrote that AyuStinc is removed, but I didn't found any AyuSync lines in comparison. How did you removed it and maybe it will be better just to set DEFAULT_AYUSYNC_SERVER to 0.0.0.0?

**Comment by Dr4iv3rNope** [comment]
1. It's safe to publish it, because [official telegram android upstream contains google-services.json](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj_App/google-services.json). This file is used to collect analytics using [Google Firebase](https://firebase.google.com/). **Only reason why it's hidden, because I don't want to receive any crash analytics from other forks**.
2. You can safely use [rewrite branch](https://github.com/Dr4iv3rNope/NotSoAndroidAyuGram/tree/rewrite). AyuSync currently is not doing any shady stuff (until it's activated) **and I hope it wont in future**. If you still want to disable AyuSync then check out [no-ayusync branch](https://github.com/Dr4iv3rNope/NotSoAndroidAyuGram/tree/no-ayusync). But currently it's not building due to errors. I will fix errors later and merge branch.
