### ISSUE TITLE
Firebase-free notifications

### ISSUE THREAD

**Issue by Miron123456** [Dr4iv3rNope/NotSoAndroidAyuGram#7]
[this is a copy of issue hidden due to flagged account]

Your reworked ayugram is great, and the only thing keeping it from being fully open source is google firebase.
Would you please implement the ability to deliver notifications without google firebase (as it is implemented in telegram foss for example)?

**Comment by Dr4iv3rNope** [comment]
I forked AyuGram only to allow users to compile this project by themselves and provide full code transparency. I don't want to continue working on this project because of a mess in this Telegram client code. And also this project is outdated because the AyuGram/exteraGram code is now proprietary.

You can fork this repository and implement feature by yourself ( and maybe create a pull request ;p )
